INSERT INTO TOYS(id, price, age, name, url) values(1,1000,5,'Ben10','https://images.app.goo.gl/evJHCxUNhWs1EwsD7')
INSERT INTO TOYS(id, price, age, name, url) values(2,1100,6,'BarbieDoll','https://images.app.goo.gl/BPQJKzSvameJinjm8')
INSERT INTO TOYS(id, price, age, name, url) values(3,1300,4,'Minion','https://images.app.goo.gl/1pNnymKb4AkuMgC17')
INSERT INTO TOYS(id, price, age, name, url) values(4,900,8,'Transformers','https://images.app.goo.gl/DUn7XQjuQjH4e4HP6')
INSERT INTO TOYS(id, price, age, name, url) values(5,200,3,'Car','https://images.app.goo.gl/PZuT6q3MuabPXX5G9')
